### ISSUE TITLE
Unexpected Token Error

### ISSUE THREAD

**Issue by riparino** [jsa2/caOptics#16]
```
$ node ./ca/main.js
/home/admin-wsl/Repos/caOptics/ca/main.js:59
    if (preP?.length == 0) {
             ^

SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
    at internal/main/run_main_module.js:17:47
```

**Comment by jsa2** [comment]
Sorry for my late response. I believe the NodeJs version you are running does not support certain aspects of CAOptics. Could you update NodeJS and reply back

Windows
https://nodejs.org/en/download

Linux (from https://nodejs.org/en/download)
```sh
# installs NVM (Node Version Manager)
curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.7/install.sh | bash

# download and install Node.js
nvm install 20

# verifies the right Node.js version is in the environment
node -v # should print `v20.12.2`

# verifies the right NPM version is in the environment
npm -v # should print `10.5.0`
```
